services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    volumes:
      - bot-wp-creds:/backend/src/bot-wp/creds
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  bot-wp-creds:
