services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    networks:
      - backend-network

networks:
  backend-network:
